@startuml

title __TEST's Class Diagram__\n

  package test {
    class JUnitTestFrameSetArray {
        - timelimit : int
        + testAddFindRetrieveDeleteWKeyDeleteWPos()
        + testUnify()
        + testArraySizeIncrease()
        + testDeleteTwice()
        + testDeleteElementNotInSet()
        + testAddTwice()
        + testAdd10()
        + testAdd1000()
        + testDeletePOS10BestCase()
        + testDeletePOS100BestCase()
        + testDeletePOS1000BestCase()
        + testDeletePOS10000BestCase()
        + testDeletePOS100000BestCase()
        + testDeletePOS10AverageCase()
        + testDeletePOS100AverageCase()
        + testDeletePOS1000AverageCase()
        + testDeletePOS10000AverageCase()
        + testDeletePOS100000AverageCase()
        + testDeletePOS10WorstCase()
        + testDeletePOS100WorstCase()
        + testDeletePOS1000WorstCase()
        + testDeletePOS10000WorstCase()
        + testDeletePOS100000WorstCase()
        + testDeleteKEY10BestCase()
        + testDeleteKEY100BestCase()
        + testDeleteKEY1000BestCase()
        + testDeleteKEY10000BestCase()
        + testDeleteKEY100000BestCase()
        + testDeleteKEY10AverageCase()
        + testDeleteKEY100AverageCase()
        + testDeleteKEY1000AverageCase()
        + testDeleteKEY10000AverageCase()
        + testDeleteKEY100000AverageCase()
        + testDeleteKEY10WorstCase()
        + testDeleteKEY100WorstCase()
        + testDeleteKEY1000WorstCase()
        + testDeleteKEY10000WorstCase()
        + testDeleteKEY100000WorstCase()
    }
  }
  

  package test {
    class JUnitTestFrameSetContainer {
        - timelimit : int
        + testAddFindRetrieveDeleteWKeyDeleteWPos()
        + testUnify()
        + testArraySizeIncrease()
        + testDeleteTwice()
        + testDeleteElementNotInSet()
        + testAddTwice()
        + testAdd10()
        + testAdd1000()
        + testDeletePOS10WorstCase()
        + testDeletePOS100WorstCase()
        + testDeletePOS1000WorstCase()
        + testDeletePOS10000WorstCase()
        + testDeletePOS100000WorstCase()
        + testDeletePOS10AverageCase()
        + testDeletePOS100AverageCase()
        + testDeletePOS1000AverageCase()
        + testDeletePOS10000AverageCase()
        + testDeletePOS100000AverageCase()
        + testDeletePOS10BestCase()
        + testDeletePOS100BestCase()
        + testDeletePOS1000BestCase()
        + testDeletePOS10000BestCase()
        + testDeletePOS100000BestCase()
        + testDeleteKEY10WorstCase()
        + testDeleteKEY100WorstCase()
        + testDeleteKEY1000WorstCase()
        + testDeleteKEY10000WorstCase()
        + testDeleteKEY100000WorstCase()
        + testDeleteKEY10AverageCase()
        + testDeleteKEY100AverageCase()
        + testDeleteKEY1000AverageCase()
        + testDeleteKEY10000AverageCase()
        + testDeleteKEY100000AverageCase()
        + testDeleteKEY10BestCase()
        + testDeleteKEY100BestCase()
        + testDeleteKEY1000BestCase()
        + testDeleteKEY10000BestCase()
        + testDeleteKEY100000BestCase()
    }
  }
  

  package test {
    class JUnitTestFrameSetContainerArray {
        - timelimit : int
        + testAddFindRetrieveDeleteWKeyDeleteWPos()
        + testUnify()
        + testArraySizeIncrease()
        + testDeleteTwice()
        + testDeleteElementNotInSet()
        + testAddTwice()
        + testAdd10()
        + testAdd1000()
        + testDeletePOS10BestCase()
        + testDeletePOS100BestCase()
        + testDeletePOS1000BestCase()
        + testDeletePOS10000BestCase()
        + testDeletePOS100000BestCase()
        + testDeletePOS10AverageCase()
        + testDeletePOS100AverageCase()
        + testDeletePOS1000AverageCase()
        + testDeletePOS10000AverageCase()
        + testDeletePOS100000AverageCase()
        + testDeletePOS10WorstCase()
        + testDeletePOS100WorstCase()
        + testDeletePOS1000WorstCase()
        + testDeletePOS10000WorstCase()
        + testDeletePOS100000WorstCase()
        + testDeleteKEY10BestCase()
        + testDeleteKEY100BestCase()
        + testDeleteKEY1000BestCase()
        + testDeleteKEY10000BestCase()
        + testDeleteKEY100000BestCase()
        + testDeleteKEY10AverageCase()
        + testDeleteKEY100AverageCase()
        + testDeleteKEY1000AverageCase()
        + testDeleteKEY10000AverageCase()
        + testDeleteKEY100000AverageCase()
        + testDeleteKEY10WorstCase()
        + testDeleteKEY100WorstCase()
        + testDeleteKEY1000WorstCase()
        + testDeleteKEY10000WorstCase()
        + testDeleteKEY100000WorstCase()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
